name: Node.js CI

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
        name: build application
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
        name: test application
      - run: pnpm run test
